settings:
  title: 'My Status Page'
  #url: 'https://status.onecf.xyz' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: liberate.cloudf.xyz# unique identifier
    name: liberate.cloudf.xyz
    description: 'Test' # default=empty
    url: 'https://liberate.cloudf.xyz' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: unifi.liberate.com
    name: unifi.liberate.com
    description: 'Unifi'
    url: 'https://unifi.liberate.cloudf.xyz'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    followRedirect: true
